---
services:
  vscodium:
    image: lscr.io/linuxserver/vscodium:latest
    container_name: vscodium
    cap_add:
      - IPC_LOCK
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=libfuse2|git|gdb
    volumes:
      - /mnt/Cloud/Data/Docker/vscodium/config:/config
      - /mnt/Cloud/Public/Docs
    ports:
      - 3040:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped